const express=require('express')
const {createCard,getCards,freeseCard,blockCard,replaceCard} =require('../controllers/card.controller')
const auth=require('../middlewares/authMiddleware')
const router=express.Router()
router.post('/createCard',createCard)
router.post('/getCards',getCards)
router.post('/freese/:id',freeseCard)
router.post('/block/:id',blockCard)
router.post('/replace/:id',replaceCard)
module.exports=router