const express=require('express')
const app=express()
const router=express.Router()
const dotenv=require('dotenv')
const authRoutes=require('./routes/auth.route')
const transactionRoutes=require('./routes/transaction.route')
const transferRoutes=require('./routes/transfer.route')
const cardRoutes=require('./routes/card.route')
const cardTransactionRoutes=require('./routes/cardTransaction.route')
const userRoutes=require('./routes/user.route')
const adminRoutes=require('./routes/admin.route')
const adminUserRoutes=require('./routes/adminUser.route')
const adminCardRoutes=require('./routes/adminCard.route')
const adminTransactionRoutes=require('./routes/adminTransaction.route')
const depositRoutes=require('./routes/deposit.route')
const notificationRoutes=require('./routes/notification.route')
const cors=require('cors')
const connectDB=require('./config/db')
const PORT=process.env.PORT || 4000
dotenv.config()
connectDB()
app.use(express.json())
app.use(cors())
app.use('/api/auth',authRoutes)
app.use('/api/transactions',transactionRoutes)
app.use('/api/card',cardRoutes)
app.use('/api/card-transactions',cardTransactionRoutes)
app.use('/api/users',userRoutes)
app.use('/api/admin',adminRoutes)
app.use('/api/admin/cards',adminCardRoutes)
app.use('/api/admin/transactions',adminTransactionRoutes)
app.use('/api/deposit',depositRoutes)
app.use('/api/notifications',notificationRoutes)
app.use('/api/transfer',transferRoutes)
app.use('/api/admin/users',adminUserRoutes)
app.listen(PORT,()=>{
    console.log(`server running on port ${PORT}`)
})